COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
NO_ACTION_ONESHOT = yes
NO_ACTION_TAPPING = yes
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
UNICODE_ENABLE = no
VIA_ENABLE = yes

